### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by Vineet2530** [Jindi0/SAFE#1]
The following code on running shows the error "case_headline.npy" not found. How to rectify this error? Where will I find this file?
![Screenshot (1)](https://user-images.githubusercontent.com/64510169/100614310-f4ea1280-333b-11eb-8132-6a0f41cfcdcf.png)

**Comment by Jindi0** [comment]
Hi, The .npy files contain the embedding of text. We have updated the README file, the final embedding results are not provided but you can find the resource of the data and embedding tool we use.

**Comment by Jindi0** [comment]
Hi, we have updated the embedding method, please have a check.
