### ISSUE TITLE
Code execution problems.

### ISSUE THREAD

**Issue by kkhanh4github** [Jindi0/SAFE#2]
Hello sir/madam
I am Kamran Khan, student of MSc. Computer Science at South Asian University Delhi.
I have read this papers, SAFE( Similarity-Aware Multi-Modal Fake News Detection), Now for some programing insight I want to run this code, but the dataset directory is not include and giving me execution errors.
My kind request is that please help me to resolve these issues.
Thank you 
regard

**Comment by Jindi0** [comment]
Hi Kamran,

We have updated the repository and provided the data resource, please check it out.
