### ISSUE TITLE
Embending problems

### ISSUE THREAD

**Issue by marcomameli1992** [Jindi0/SAFE#3]
Dear the embending SIF has some problems. Can you provide a tutorial or the code to use your file for embending because the SIF that you have linked and the examples present in it are not clear. For example I have download the word that you provide and now how have to use it in the SIF? 
After that how and what I have to save?

I think this information is very important to reproduce your results and to start my study in this environment. 

Thank you for your availability.

**Comment by marcomameli1992** [comment]
To be more clear: Can you explain the procedure and the code of SIF that you have used to obtain the npy in the training stage?

**Comment by Jindi0** [comment]
You will get the SIF version that adjusts to SAFE in the "embedding" branch of this repository.
